CREATE TABLE USERS(
        ID INTEGER PRIMARY KEY AUTO_INCREMENT,
        EMAIL VARCHAR(100),
        PASSWORD VARCHAR(100),
        ROLE VARCHAR(100)

)
CREATE TABLE CLIENT(
       ID INTEGER PRIMARY KEY AUTO_INCREMENT,
       NAME VARCHAR(100),
       CPF VARCHAR(11)
);
CREATE TABLE PRODUCT(
       ID INTEGER PRIMARY KEY AUTO_INCREMENT,
       DESCRIPTION VARCHAR(100),
       UNIT_PRICE NUMERIC(20,2),
       STATUS VARCHAR(20)
);
CREATE TABLE ORDERS(
       ID INTEGER PRIMARY KEY AUTO_INCREMENT,
       CLIENT_ID INTEGER REFERENCES CLIENT(ID),
       DATE_ORDER TIMESTAMP,
       TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_ORDER(
       ID INTEGER PRIMARY KEY AUTO_INCREMENT,
        ORDER_ID INTEGER REFERENCES ORDERS (ID),
         PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
         QUANTITY INTEGER

);